### ISSUE TITLE
why client just receive first one message?

### ISSUE THREAD

**Issue by wenjun001** [eProsima/micro-RTPS-client#2]
I send lots of messages from standard DDS publisher 
such as:
Publisher matched
Message: go with index: 1 SENT
Message: go with index: 2 SENT
Message: go with index: 3 SENT
Message: go with index: 4 SENT
Message: go with index: 5 SENT
Message: go with index: 6 SENT
Message: go with index: 7 SENT
Message: go with index: 8 SENT
Message: go with index: 9 SENT
Message: go with index: 10 SENT

but when i try to subscrib it in client  and just receive one
 
<== [Data | #0xFF00 | id: 0x0004 | from #0xFF00 | NONE | OK | FORMAT_DATA | size: 12]
on_hello_topic

**Comment by lemunozm** [comment]
Hi @wenjun001, the problem you commented could be a possible bug that is fixed in the last version. Please, download it, and let us know if the problem persist.
