### ISSUE TITLE
subscriber will crash when try to free topic 

### ISSUE THREAD

**Issue by wenjun001** [eProsima/micro-RTPS-client#3]
when we call 

    free(topic->m_message);
    free(topic);

in void on_hello_topic(XRCEInfo info, const void* vtopic, void* args)

** Error in `./read': munmap_chunk(): invalid pointer: 0x00007f422282f260 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f42222c47e5]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7f42222d1698]
./read[0x400ecf]
./read[0x407dbf]
./read[0x40f91b]
./read[0x40fc8b]
./read[0x408c4b]
./read[0x4010b6]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f422261e6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f422235441d]
======= Memory map: ========
00400000-00416000 r-xp 00000000 fc:00 29495744                           /home/wma/eProsima/micro-RTPS/micro-RTPS-client/examples/quickhelloworld/read
00615000-00616000 r--p 00015000 fc:00 29495744                           /home/wma/eProsima/micro-RTPS/micro-RTPS-client/examples/quickhelloworld/read
00616000-00617000 rw-p 00016000 fc:00 29495744                           /home/wma/eProsima/micro-RTPS/micro-RTPS-client/examples/quickhelloworld/read
00617000-00618000 rw-p 00000000 00:00 0 
0087e000-0089f000 rw-p 00000000 00:00 0                                  [heap]
7f421c000000-7f421c021000 rw-p 00000000 00:00 0 
7f421c021000-7f4220000000 ---p 00000000 00:00 0 
7f4221836000-7f422184c000 r-xp 00000000 fc:00 8393101                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f422184c000-7f4221a4b000 ---p 00016000 fc:00 8393101                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4221a4b000-7f4221a4c000 rw-p 00015000 fc:00 8393101                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4221a4c000-7f4221a4d000 ---p 00000000 00:00 0 
7f4221a4d000-7f422224d000 rw-p 00000000 00:00 0 
7f422224d000-7f422240d000 r-xp 00000000 fc:00 8395368                    /lib/x86_64-linux-gnu/libc-2.23.so
7f422240d000-7f422260d000 ---p 001c0000 fc:00 8395368                    /lib/x86_64-linux-gnu/libc-2.23.so
7f422260d000-7f4222611000 r--p 001c0000 fc:00 8395368                    /lib/x86_64-linux-gnu/libc-2.23.so
7f4222611000-7f4222613000 rw-p 001c4000 fc:00 8395368                    /lib/x86_64-linux-gnu/libc-2.23.so
7f4222613000-7f4222617000 rw-p 00000000 00:00 0 
7f4222617000-7f422262f000 r-xp 00000000 fc:00 8395367                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f422262f000-7f422282e000 ---p 00018000 fc:00 8395367                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f422282e000-7f422282f000 r--p 00017000 fc:00 8395367                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f422282f000-7f4222830000 rw-p 00018000 fc:00 8395367                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4222830000-7f4222834000 rw-p 00000000 00:00 0 
7f4222834000-7f4222838000 r-xp 00000000 fc:00 16646175                   /usr/local/lib/libtransport.so
7f4222838000-7f4222a37000 ---p 00004000 fc:00 16646175                   /usr/local/lib/libtransport.so
7f4222a37000-7f4222a38000 r--p 00003000 fc:00 16646175                   /usr/local/lib/libtransport.so
7f4222a38000-7f4222a39000 rw-p 00004000 fc:00 16646175                   /usr/local/lib/libtransport.so
7f4222a39000-7f4222a5f000 r-xp 00000000 fc:00 8395363                    /lib/x86_64-linux-gnu/ld-2.23.so
7f4222c14000-7f4222c18000 rw-p 00000000 00:00 0 
7f4222c5d000-7f4222c5e000 rw-p 00000000 00:00 0 
7f4222c5e000-7f4222c5f000 r--p 00025000 fc:00 8395363                    /lib/x86_64-linux-gnu/ld-2.23.so
7f4222c5f000-7f4222c60000 rw-p 00026000 fc:00 8395363                    /lib/x86_64-linux-gnu/ld-2.23.so
7f4222c60000-7f4222c61000 rw-p 00000000 00:00 0 
7ffd635e9000-7ffd6360b000 rw-p 00000000 00:00 0                          [stack]
7ffd637f8000-7ffd637fb000 r--p 00000000 00:00 0                          [vvar]
7ffd637fb000-7ffd637fd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
  message----- Aborted (core dumped)

**Comment by lemunozm** [comment]
Hi @wenjun001, sorry for not responding before, we have a new version that is not using dynamic memory: v1.0.0.
