### ISSUE TITLE
Delete a specific entity resource.

### ISSUE THREAD

**Issue by OpusK** [eProsima/micro-RTPS-client#8]
Hi,

The client has an API to remove the session.
However, there is no API to delete each Entity.
I want to delete Entity only while maintaining Session.

Do you plan to add these APIs?

**Comment by lemunozm** [comment]
Hi @OpusK,

I think the function you are looking for is the following:
```c
uint16_t mr_write_delete_entity(mrSession* session, mrStreamId stream_id, mrObjectId object_id);
```
It is placed in `include/micrortps/client/profile/session/common_create_entities.h` and is included automatically when you include `client.h` if you have enable the `PROFILE_CREATE_ENTITIES_REF` or `PROFILE_CREATE_ENTITIES_XML` into `client.config` file.

**Comment by OpusK** [comment]
Hi, @lemunozm. 

Thank you! It works well as I want!
